# Generated by Django 4.1 on 2022-08-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csi_Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_image', models.ImageField(upload_to='images')),
                ('event_description', models.TextField(max_length=500)),
                ('event_link', models.URLField()),
                ('event_feeBool', models.BooleanField(default=False)),
                ('event_fee', models.IntegerField(default=0)),
            ],
        ),
    ]
