# Generated by Django 4.1 on 2022-08-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csi_event',
            name='event_fee',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='csi_event',
            name='event_link',
            field=models.URLField(blank=True),
        ),
    ]
