# Generated by Django 4.1 on 2022-08-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.TextField(max_length=70)),
                ('member_position', models.TextField(max_length=20)),
                ('member_image', models.ImageField(upload_to='images')),
                ('member_linkedIn', models.URLField()),
                ('member_instagram', models.URLField()),
            ],
        ),
    ]
