# Generated by Django 4.1 on 2022-08-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_position',
            field=models.CharField(max_length=20),
        ),
    ]
