# Generated by Django 4.1 on 2022-08-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_member_member_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='member_instagram',
        ),
        migrations.AddField(
            model_name='member',
            name='member_github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_linkedIn',
            field=models.URLField(blank=True),
        ),
    ]
